platform :ios, '8.0'
use_frameworks!

target 'StatusBarOverlay' do
    # swift
    pod 'ReachabilitySwift', '~> 5.0.0' # https://github.com/ashleymills/Reachability.swift
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
